
insert into USUARIO(NOME,EMAIL,CPF,SENHA)VALUES('admin','admin','CPFADMIN','21232f297a57a5a743894a0e4a801fc3');
insert into USUARIO(NOME,EMAIL,CPF,SENHA)VALUES('user','user','CPFUSER','ee11cbb19052e40b07aac0ca060c23ee');
insert into PERMISSAO(NOME)VALUES('ROLE_ADMIN');
insert into PERMISSAO(NOME)VALUES('ROLE_USER');
insert into USUARIO_PERMISSAO(USUARIO_ID,PERMISSOES_NOME)VALUES(1,'ROLE_ADMIN');
insert into USUARIO_PERMISSAO(USUARIO_ID,PERMISSOES_NOME)VALUES(1,'ROLE_USER');
